'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language =
  | 'en'
  | 'hi'
  | 'gu'
  | 'mr'
  | 'bn'
  | 'ta'
  | 'te'
  | 'kn'
  | 'ml'
  | 'pa'
  | 'es'
  | 'fr'
  | 'de'
  | 'ar'
  | 'zh'
  | 'ja'
  | 'ru';

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  region: string;
  dir?: 'ltr' | 'rtl';
}

export const supportedLanguages: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English (US)', region: 'International' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'India' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'India' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'India' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'India / Bangladesh' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'India / Sri Lanka / Singapore' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'India' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'India' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'India' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'India' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', region: 'Spain / Latin America' },
  { code: 'fr', name: 'French', nativeName: 'Français', region: 'France / Canada' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', region: 'Germany / EU' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', region: 'Middle East / North Africa', dir: 'rtl' },
  { code: 'zh', name: 'Mandarin Chinese', nativeName: '简体中文', region: 'China / Singapore' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', region: 'Japan' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', region: 'Eastern Europe / Central Asia' },
];

export const dictionary: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.dashboard': {
    en: 'Dashboard',
    hi: 'डैशबोर्ड',
    gu: 'ડેશબોર્ડ',
    mr: 'डॅशबोर्ड',
    bn: 'ড্যাশবোর্ড',
    ta: 'டாஷ்போர்டு',
    te: 'డ్యాష్‌బోర్డ్',
    kn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    ml: 'ഡാഷ്‌ബോർഡ്',
    pa: 'ਡੈਸ਼ਬੋਰਡ',
    es: 'Panel de Control',
    fr: 'Tableau de Bord',
    de: 'Dashboard',
    ar: 'لوحة التحكم',
    zh: '仪表板',
    ja: 'ダッシュボード',
    ru: 'Панель управления',
  },
  'nav.verify': {
    en: 'Verify Document',
    hi: 'दस्तावेज़ सत्यापन',
    gu: 'દસ્તાવેજ ચકાસણી',
    mr: 'दस्तऐवज पडताळणी',
    bn: 'নথি যাচাইকরণ',
    ta: 'ஆவண சரிபார்ப்பு',
    te: 'పత్రం ధృవీకరణ',
    kn: 'ದಾಖಲೆ ಪರಿಶೀಲನೆ',
    ml: 'രേഖ പരിശോധന',
    pa: 'ਦਸਤਾਵੇਜ਼ ਤਸਦੀਕ',
    es: 'Verificar Documento',
    fr: 'Vérifier le Document',
    de: 'Dokument Verifizieren',
    ar: 'التحقق من الوثيقة',
    zh: '验证文件',
    ja: 'ドキュメント検証',
    ru: 'Проверка документа',
  },
  'nav.quickScreen': {
    en: 'Quick Screening',
    hi: 'त्वरित स्क्रीनिंग',
    gu: 'ઝડપી સ્ક્રિનિંગ',
    mr: 'जलद स्क्रिनिंग',
    bn: 'দ্রুত স্ক্রিনিং',
    ta: 'விரைவு பரிசோதனை',
    te: 'త్వరిత స్క్రీనింగ్',
    kn: 'ತ್ವರಿತ ತಪಾಸಣೆ',
    ml: 'ദ്രുത സ്ക്രീനിംഗ്',
    pa: 'ਤੇਜ਼ ਸਕ੍ਰੀਨਿੰਗ',
    es: 'Inspección Rápida',
    fr: 'Filtrage Rapide',
    de: 'Schnellprüfung',
    ar: 'الفحص السريع',
    zh: '快速甄别',
    ja: 'クイックスクリーニング',
    ru: 'Быстрый скрининг',
  },
  'nav.reviewDesk': {
    en: 'Forensic Review Desk',
    hi: 'फोरेंसिक समीक्षा डेस्क',
    gu: 'ફોરેન્સિક સમીક્ષા ડેસ્ક',
    mr: 'फॉरेन्सिक पुनरावलोकन डेस्क',
    bn: 'ফরেনসিক পর্যালোচনা ডেস্ক',
    ta: 'தடயவியல் மதிப்பாய்வு டெஸ்க்',
    te: 'ఫోరెన్సిక్ రివ్యూ డెస్క్',
    kn: 'ಫೋರೆನ್ಸಿಕ್ ಪರಿಶೀಲನಾ ಡೆಸ್ಕ್',
    ml: 'ഫോറൻസിക് റിവ്യൂ ഡെസ്ക്',
    pa: 'ਫੋਰੈਂਸਿਕ ਸਮੀਖਿਆ ਡੈਸਕ',
    es: 'Mesa de Revisión Forense',
    fr: 'Poste d’Examen Médico-légal',
    de: 'Forensik-Prüfplatz',
    ar: 'مكتب المراجعة الجنائية',
    zh: '司法取证审查台',
    ja: 'フォレンジック審査デスク',
    ru: 'Криминалистический стол',
  },
  'nav.travelerProfile': {
    en: 'Traveler Profile',
    hi: 'यात्री प्रोफ़ाइल',
    gu: 'મુસાફર પ્રોફાઇલ',
    mr: 'प्रवासी प्रोफाइल',
    bn: 'যাত্রী প্রোফাইল',
    ta: 'பயணி விவரக்குறிப்பு',
    te: 'ప్రయాణీకుల ప్రొఫైల్',
    kn: 'ಪ್ರಯಾಣಿಕರ ಪ್ರೊಫೈಲ್',
    ml: 'യാത്രക്കാരന്റെ പ്രൊഫൈൽ',
    pa: 'ਯਾਤਰੀ ਪ੍ਰੋਫਾਈਲ',
    es: 'Perfil del Viajero',
    fr: 'Profil du Voyageur',
    de: 'Reisenden-Profil',
    ar: 'ملف المسافر',
    zh: '旅客综合档案',
    ja: '渡航者プロファイル',
    ru: 'Профиль путешественника',
  },
  'nav.history': {
    en: 'Audit History',
    hi: 'सत्यापन इतिहास',
    gu: 'ઓડિટ ઇતિહાસ',
    mr: 'ऑडिट इतिहास',
    bn: 'নিরীক্ষা ইতিহাস',
    ta: 'தணிக்கை வரலாறு',
    te: 'ఆడిట్ చరిత్ర',
    kn: 'ಆಡಿಟ್ ಇತಿಹಾಸ',
    ml: 'ഓഡിറ്റ് ചരിത്രം',
    pa: 'ਆਡਿਟ ਇਤਿਹਾਸ',
    es: 'Historial de Auditoría',
    fr: 'Historique d’Audit',
    de: 'Prüfverlauf',
    ar: 'سجل التدقيق',
    zh: '审核历史',
    ja: '監査履歴',
    ru: 'История аудита',
  },
  'nav.reports': {
    en: 'Forensic Reports',
    hi: 'रिपोर्ट्स एवं डोज़ियर',
    gu: 'અહેવાલો',
    mr: 'अहवाल',
    bn: 'ফরেনসিক রিপোর্ট',
    ta: 'அறிக்கைகள்',
    te: 'నివేదికలు',
    kn: 'ವರದಿಗಳು',
    ml: 'റിപ്പോർട്ടുകൾ',
    pa: 'ਰਿਪੋਰਟਾਂ',
    es: 'Informes Forenses',
    fr: 'Rapports Légaux',
    de: 'Forensische Berichte',
    ar: 'التقارير الجنائية',
    zh: '取证报告',
    ja: '鑑定レポート',
    ru: 'Экспертные отчеты',
  },
  'nav.modelInsights': {
    en: 'Model Insights',
    hi: 'मॉडल इनसाइट्स',
    gu: 'મોડેલ ઇનસાઇટ્સ',
    mr: 'मॉडेल इनसाइट्स',
    bn: 'মডেল ইনসাইট',
    ta: 'மாதிரி நுண்ணறிவு',
    te: 'మోడల్ అంతర్దృష్టులు',
    kn: 'ಮಾದರಿ ಒಳನೋಟಗಳು',
    ml: 'മോഡൽ സ്ഥിതിവിവരക്കണക്കുകൾ',
    pa: 'ਮਾਡਲ ਇਨਸਾਈਟਸ',
    es: 'Métricas de Modelos',
    fr: 'Analyses des Modèles',
    de: 'Modell-Einblicke',
    ar: 'تحليلات النماذج',
    zh: '模型指标洞察',
    ja: 'AIモデル指標',
    ru: 'Метрики моделей',
  },
  'nav.settings': {
    en: 'Settings',
    hi: 'सेटिंग्स',
    gu: 'સેટિંગ્સ',
    mr: 'सेटिंग्ज',
    bn: 'সেটিংস',
    ta: 'அமைப்புகள்',
    te: 'సెట్టింగ్‌లు',
    kn: 'ಸಂಯೋಜನೆಗಳು',
    ml: 'ക്രമീകരണങ്ങൾ',
    pa: 'ਸੈਟਿੰਗਾਂ',
    es: 'Configuración',
    fr: 'Paramètres',
    de: 'Einstellungen',
    ar: 'الإعدادات',
    zh: '系统设置',
    ja: 'システム設定',
    ru: 'Настройки',
  },
  'nav.login': {
    en: 'Sign In / Account',
    hi: 'साइन इन / खाता',
    gu: 'સાઇન ઇન / ખાતું',
    mr: 'साइन इन / खाते',
    bn: 'সাইন ইন / অ্যাকাউন্ট',
    ta: 'உள்நுழை / கணக்கு',
    te: 'సైన్ ఇన్ / ఖాతా',
    kn: 'ಸೈನ್ ಇನ್ / ಖಾತೆ',
    ml: 'സൈൻ ഇൻ / അക്കൗണ്ട്',
    pa: 'ਸਾਈਨ ਇਨ / ਖਾਤਾ',
    es: 'Iniciar Sesión / Cuenta',
    fr: 'Connexion / Compte',
    de: 'Anmelden / Konto',
    ar: 'تسجيل الدخول / الحساب',
    zh: '登录 / 账户',
    ja: 'ログイン / アカウント',
    ru: 'Вход / Аккаунт',
  },
  'nav.systemOnline': {
    en: 'Forensic Engine Online',
    hi: 'सत्यापन इंजन सक्रिय है',
    gu: 'ફોરેન્સિક એન્જિન સક્રિય છે',
    mr: 'फॉरेन्सिक इंजिन ऑनलाइन आहे',
    bn: 'ফরেনসিক ইঞ্জিন সক্রিয়',
    ta: 'தடயவியல் எஞ்சின் ஆன்லைனில் உள்ளது',
    te: 'ఫోరెన్సిక్ ఇంజిన్ ఆన్‌లైన్‌లో ఉంది',
    kn: 'ಫೋರೆನ್ಸಿಕ್ ಎಂಜಿನ್ ಆನ್‌ಲೈನ್‌ನಲ್ಲಿದೆ',
    ml: 'ഫോറൻസിക് എഞ്ചിൻ സജീവമാണ്',
    pa: 'ਫੋਰੈਂਸਿਕ ਇੰਜਣ ਔਨਲਾਈਨ ਹੈ',
    es: 'Motor Forense en Línea',
    fr: 'Moteur Forensique en Ligne',
    de: 'Forensik-Engine Online',
    ar: 'المحرك الجنائي متصل',
    zh: '智能取证引擎在线',
    ja: '鑑定エンジン稼働中',
    ru: 'Криминалистический модуль активен',
  },

  // Hero & Headlines
  'hero.tagline': {
    en: 'BORDER SECURITY & IDENTITY INTELLIGENCE',
    hi: 'सीमा सुरक्षा और पहचान विश्लेषण',
    gu: 'સરહદ સુરક્ષા અને ઓળખ બુદ્ધિમત્તા',
    mr: 'सीमा सुरक्षा आणि ओळख बुद्धिमत्ता',
    bn: 'সীমান্ত সুরক্ষা ও পরিচয় গোয়েন্দা',
    ta: 'எல்லைப் பாதுகாப்பு & அடையாள நுண்ணறிவு',
    te: 'సరిహద్దు భద్రత & గుర్తింపు ఇంటెలిజెన్స్',
    kn: 'ಗಡಿ ಭದ್ರತೆ & ಗುರುತಿನ ಬುದ್ಧಿಮತ್ತೆ',
    ml: 'അതിർത്തി സുരക്ഷയും തിരിച്ചറിയൽ ഇന്റലിജൻസും',
    pa: 'ਸਰਹੱਦੀ ਸੁਰੱਖਿਆ ਅਤੇ ਪਛਾਣ ਖੁਫੀਆ',
    es: 'SEGURIDAD FRONTERIZA E INTELIGENCIA DE IDENTIDAD',
    fr: 'SÉCURITÉ FRONTALIÈRE & RENSEIGNEMENT D’IDENTITÉ',
    de: 'GRENZSCHUTZ & IDENTITÄTS-INTELLIGENZ',
    ar: 'أمن الحدود واستخبارات الهوية',
    zh: '边境安全与身份智能取证',
    ja: '国境警備・身元識別インテリジェンス',
    ru: 'ПОГРАНИЧНАЯ БЕЗОПАСНОСТЬ И ИДЕНТИФИКАЦИЯ',
  },
  'hero.headline': {
    en: 'Know before you approve.',
    hi: 'स्वीकृति से पहले सत्य जानें।',
    gu: 'મંજૂરી આપતા પહેલા સત્ય જાણો.',
    mr: 'मंजुरी देण्यापूर्वी सत्य जाणून घ्या.',
    bn: 'অনুমোদনের আগে সত্য জানুন।',
    ta: 'ஒப்புதலுக்கு முன் உண்மையை அறியுங்கள்.',
    te: 'ఆమోదించడానికి ముందు నిజాన్ని తెలుసుకోండి.',
    kn: 'ಅನುಮೋದಿಸುವ ಮೊದಲು ಸತ್ಯವನ್ನು ತಿಳಿಯಿರಿ.',
    ml: 'അംഗീകരിക്കുന്നതിന് മുമ്പ് യാഥാർത്ഥ്യം അറിയുക.',
    pa: 'ਮਨਜ਼ੂਰੀ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਸੱਚ ਜਾਣੋ।',
    es: 'Conozca antes de aprobar.',
    fr: 'Sachez avant d’approuver.',
    de: 'Prüfen vor der Genehmigung.',
    ar: 'اعلم قبل أن توافق.',
    zh: '批准之前，明察秋毫。',
    ja: '承認する前に、真偽を見抜く。',
    ru: 'Убедитесь перед утверждением.',
  },
  'hero.subtitle': {
    en: 'Verify identity documents, detect tampering, and cross-reference records with multi-modal AI models in seconds.',
    hi: 'दस्तावेज़ों का सत्यापन करें, छेड़छाड़ का पता लगाएं और मल्टी-मॉडल AI से रिकॉर्ड्स की त्वरित जांच करें।',
    gu: 'દસ્તાવેજો ચકાસો, છેડછાડ શોધો અને સેકન્ડોમાં રેકોર્ડ તપાસો.',
    mr: 'दस्तऐवज पडताळा, छेडछाड ओळखा आणि सेकंदात रेकॉर्ड्स तपासा.',
    bn: 'নথি যাচাই করুন, জালিয়াতি শনাক্ত করুন এবং সেকেন্ডের মধ্যে রেকর্ড যাচাই করুন।',
    ta: 'ஆவணங்களை சரிபார்க்கவும், முறைகேடுகளைக் கண்டறியவும், நொடிகளில் தரவுகளை ஒப்பிடவும்.',
    te: 'పత్రాలను ధృవీకరించండి, ట్యాంపరింగ్‌ను గుర్తించండి మరియు సెకన్లలో రికార్డులను తనిఖీ చేయండి.',
    kn: 'ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ತಿದ್ದುವಿಕೆಯನ್ನು ಪತ್ತೆಹಚ್ಚಿ ಮತ್ತು ಕ್ಷಣಗಳಲ್ಲಿ ದಾಖಲೆಗಳನ್ನು ತಾಳೆನೋಡಿ.',
    ml: 'രേഖകൾ പരിശോധിക്കുക, തിരിമറികൾ കണ്ടെത്തുക, നിമിഷങ്ങൾക്കകം റെക്കോർഡുകൾ താരതമ്യം ചെയ്യുക.',
    pa: 'ਦਸਤਾਵੇਜ਼ਾਂ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ, ਛੇੜਛਾੜ ਲੱਭੋ ਅਤੇ ਸਕਿੰਟਾਂ ਵਿੱਚ ਰਿਕਾਰਡਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।',
    es: 'Verifique documentos de identidad, detecte alteraciones y coteje registros con IA multimodal en segundos.',
    fr: 'Vérifiez les pièces d’identité, détectez les falsifications et croisez les registres par IA multimodale en quelques secondes.',
    de: 'Identitätsdokumente prüfen, Fälschungen erkennen und Register in Sekundenschnelle mit multimodaler KI abgleichen.',
    ar: 'تحقق من وثائق الهوية، واكشف التلاعب، وقارن السجلات بالذكاء الاصطناعي متعدد الوسائط في ثوانٍ.',
    zh: '秒级核验身份证件、侦测篡改痕迹，并依托多模态AI模型比对跨境官方记录。',
    ja: 'マルチモーダルAIにより、身分証の真正性検証、偽造検知、公的照合を数秒で完了。',
    ru: 'Проверяйте документы, выявляйте следы фальсификаций и сверяйте реестры с помощью мультимодального ИИ за секунды.',
  },
  'hero.startVerification': {
    en: 'Start Verification',
    hi: 'सत्यापन शुरू करें',
    gu: 'ચકાસણી શરૂ કરો',
    mr: 'पडताळणी सुरू करा',
    bn: 'যাচাইকরণ শুরু করুন',
    ta: 'சரிபார்ப்பைத் தொடங்கு',
    te: 'ధృవీకరణ ప్రారంభించండి',
    kn: 'ಪರಿಶೀಲನೆ ಪ್ರಾರಂಭಿಸಿ',
    ml: 'പരിശോധന ആരംഭിക്കുക',
    pa: 'ਤਸਦੀਕ ਸ਼ੁਰੂ ਕਰੋ',
    es: 'Iniciar Verificación',
    fr: 'Démarrer la Vérification',
    de: 'Prüfung Starten',
    ar: 'بدء التحقق',
    zh: '开始全面验证',
    ja: '検証を開始',
    ru: 'Начать проверку',
  },
  'hero.viewHistory': {
    en: 'View Audit Log',
    hi: 'ऑडिट लॉग देखें',
    gu: 'ઓડિટ લોગ જુઓ',
    mr: 'ऑडिट लॉग पहा',
    bn: 'অডিট লগ দেখুন',
    ta: 'தணிக்கைப் பதிவைக் காண்க',
    te: 'ఆడిట్ లాగ్ చూడండి',
    kn: 'ಆಡಿಟ್ ಲಾಗ್ ವೀಕ್ಷಿಸಿ',
    ml: 'ഓഡിറ്റ് ലോഗ് കാണുക',
    pa: 'ਆਡਿਟ ਲੌਗ ਦੇਖੋ',
    es: 'Ver Registro de Auditoría',
    fr: 'Voir le Journal d’Audit',
    de: 'Prüfprotokoll Anzeigen',
    ar: 'عرض سجل التدقيق',
    zh: '查看审计日志',
    ja: '監査ログを表示',
    ru: 'Журнал аудита',
  },

  // Stats
  'stat.totalVerifications': {
    en: 'Documents Audited',
    hi: 'सत्यापित दस्तावेज़',
    gu: 'ઓડિટ થયેલ દસ્તાવેજો',
    mr: 'ऑडिट केलेले दस्तऐवज',
    bn: 'অডিট করা নথি',
    ta: 'தணிக்கை செய்யப்பட்ட ஆவணங்கள்',
    te: 'ఆడిట్ చేయబడిన పత్రాలు',
    kn: 'ಆಡಿಟ್ ಮಾಡಲಾದ ದಾಖಲೆಗಳು',
    ml: 'ഓഡിറ്റ് ചെയ്ത രേഖകൾ',
    pa: 'ਆਡਿਟ ਕੀਤੇ ਦਸਤਾਵੇਜ਼',
    es: 'Documentos Auditados',
    fr: 'Documents Audités',
    de: 'Geprüfte Dokumente',
    ar: 'الوثائق المدققة',
    zh: '已审核证件总数',
    ja: '検証済みドキュメント',
    ru: 'Проверено документов',
  },
  'stat.highRisk': {
    en: 'High Risk / Fraud Detected',
    hi: 'उच्च जोखिम पाए गए',
    gu: 'ઉચ્ચ જોખમ જણાયું',
    mr: 'उच्च धोका आढळला',
    bn: 'উচ্চ ঝুঁকি শনাক্ত',
    ta: 'அதிக ஆபத்து கண்டறியப்பட்டது',
    te: 'అధిక ప్రమాదం గుర్తించబడింది',
    kn: 'ಹೆಚ್ಚಿನ ಅಪಾಯ ಪತ್ತೆಯಾಗಿದೆ',
    ml: 'ഉയർന്ന അപകടസാധ്യത കണ്ടെത്തി',
    pa: 'ਉੱਚ ਜੋਖਮ ਪਾਇਆ ਗਿਆ',
    es: 'Alto Riesgo / Fraude Detectado',
    fr: 'Haut Risque / Fraude Détectée',
    de: 'Hohes Risiko / Betrug Erkannt',
    ar: 'مخاطر عالية / احتيال مكتشف',
    zh: '高风险 / 疑似欺诈',
    ja: '高リスク・不正検知',
    ru: 'Высокий риск / Подделки',
  },
  'stat.authentic': {
    en: 'Confirmed Authentic',
    hi: 'प्रमाणिक दस्तावेज़',
    gu: 'પ્રમાણિત અધિકૃત',
    mr: 'अस्सल पुष्टी',
    bn: 'নিশ্চিত প্রামাণিক',
    ta: 'உறுதிப்படுத்தப்பட்ட அசல்',
    te: 'ధృవీకరించబడిన అసలైనది',
    kn: 'ದೃಢೀಕೃತ ಅಧಿಕೃತ',
    ml: 'സ്ഥിരീകരിച്ച യഥാർത്ഥ രേഖ',
    pa: 'ਪ੍ਰਮਾਣਿਤ ਅਸਲੀ',
    es: 'Autenticidad Confirmada',
    fr: 'Authenticité Confirmée',
    de: 'Echtheit Bestätigt',
    ar: 'مؤكد الأصالة',
    zh: '确认真实有效',
    ja: '真正確認済み',
    ru: 'Подтверждена подлинность',
  },
  'stat.review': {
    en: 'Officer Review Required',
    hi: 'समीक्षा आवश्यक',
    gu: 'અધિકારી સમીક્ષા જરૂરી',
    mr: 'अधिकारी पुनरावलोकन आवश्यक',
    bn: 'অফিসার পর্যালোচনা প্রয়োজন',
    ta: 'அதிகாரி மதிப்பாய்வு தேவை',
    te: 'అధికారి సమీక్ష అవసరం',
    kn: 'ಅಧಿಕಾರಿಯ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ',
    ml: 'ഓഫീസർ അവലോകനം ആവശ്യമാണ്',
    pa: 'ਅਧਿਕਾਰੀ ਸਮੀਖਿਆ ਦੀ ਲੋੜ ਹੈ',
    es: 'Revisión por Oficial Requerida',
    fr: 'Examen par Agent Requis',
    de: 'Offiziersprüfung Erforderlich',
    ar: 'مراجعة الضابط مطلوبة',
    zh: '需人工关员复审',
    ja: '審査官による確認要',
    ru: 'Требуется проверка инспектором',
  },
  'stat.vsLastWeek': {
    en: 'vs. previous cycle',
    hi: 'पिछले चक्र की तुलना में',
    gu: 'પાછલા ચક્રની સરખામણીએ',
    mr: 'मागील चक्राच्या तुलनेत',
    bn: 'আগের চক্রের তুলনায়',
    ta: 'முந்தைய சுழற்சியை விட',
    te: 'మునుపటి చక్రంతో పోలిస్తే',
    kn: 'ಹಿಂದಿನ ಚಕ್ರಕ್ಕೆ ಹೋಲಿಸಿದರೆ',
    ml: 'മുമ്പത്തെ ചക്രവുമായി താരതമ്യം ചെയ്യുമ്പോൾ',
    pa: 'ਪਿਛਲੇ ਚੱਕਰ ਦੇ ਮੁਕਾਬਲੇ',
    es: 'vs. ciclo anterior',
    fr: 'vs. cycle précédent',
    de: 'ggü. vorherigem Zyklus',
    ar: 'مقارنة بالدورة السابقة',
    zh: '环比上期',
    ja: '前サイクル比',
    ru: 'к прошлому периоду',
  },

  // Actions & Buttons
  'btn.continue': {
    en: 'Continue',
    hi: 'आगे बढ़ें',
    gu: 'આગળ વધો',
    mr: 'पुढे जा',
    bn: 'এগিয়ে যান',
    ta: 'தொடரவும்',
    te: 'కొనసాగించండి',
    kn: 'ಮುಂದುವರಿಯಿರಿ',
    ml: 'തുടരുക',
    pa: 'ਜਾਰੀ ਰੱਖੋ',
    es: 'Continuar',
    fr: 'Continuer',
    de: 'Fortfahren',
    ar: 'متابعة',
    zh: '继续',
    ja: '次へ進む',
    ru: 'Продолжить',
  },
  'btn.back': {
    en: 'Back',
    hi: 'पीछे जाएं',
    gu: 'પાછા જાઓ',
    mr: 'मागे जा',
    bn: 'ফিরে যান',
    ta: 'பின்செல்',
    te: 'వెనుకకు',
    kn: 'ಹಿಂದೆ',
    ml: 'പിന്നോട്ട്',
    pa: 'ਪਿੱਛੇ',
    es: 'Atrás',
    fr: 'Retour',
    de: 'Zurück',
    ar: 'رجوع',
    zh: '返回',
    ja: '戻る',
    ru: 'Назад',
  },
  'btn.skip': {
    en: 'Skip / Continue',
    hi: 'छोड़ें / आगे बढ़ें',
    gu: 'છોડો / આગળ વધો',
    mr: 'वगळा / पुढे जा',
    bn: 'এড়িয়ে যান',
    ta: 'தவிர் / தொடரவும்',
    te: 'దాటవేయి / కొనసాగించు',
    kn: 'ಬಿಟ್ಟುಬಿಡಿ / ಮುಂದುವರಿಯಿರಿ',
    ml: 'ഒഴിവാക്കുക / തുടരുക',
    pa: 'ਛੱਡੋ / ਜਾਰੀ ਰੱਖੋ',
    es: 'Omitir / Continuar',
    fr: 'Passer / Continuer',
    de: 'Überspringen / Weiter',
    ar: 'تخطي / متابعة',
    zh: '跳过并继续',
    ja: 'スキップして続行',
    ru: 'Пропустить / Далее',
  },
  'btn.analyze': {
    en: 'Execute Forensic Analysis',
    hi: 'दस्तावेज़ का विश्लेषण करें',
    gu: 'ફોરેન્સિક વિશ્લેષણ ચલાવો',
    mr: 'फॉरेन्सिक विश्लेषण चालवा',
    bn: 'ফরেনসিক বিশ্লেষণ চালান',
    ta: 'தடயவியல் பகுப்பாய்வை இயக்கு',
    te: 'ఫోరెన్సిక్ విశ్లేషణను అమలు చేయండి',
    kn: 'ಫೋರೆನ್ಸಿಕ್ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಕಾರ್ಯಗತಗೊಳಿಸಿ',
    ml: 'ഫോറൻസിക് വിശകലനം നടത്തുക',
    pa: 'ਫੋਰੈਂਸਿਕ ਵਿਸ਼ਲੇਸ਼ਣ ਚਲਾਓ',
    es: 'Ejecutar Análisis Forense',
    fr: 'Exécuter l’Analyse Légale',
    de: 'Forensische Analyse Starten',
    ar: 'تنفيذ التحليل الجنائي',
    zh: '执行深度司法鉴定',
    ja: '法医学的解析を実行',
    ru: 'Запустить криминалистический анализ',
  },
  'btn.save': {
    en: 'Save Settings',
    hi: 'सेटिंग्स सहेजें',
    gu: 'સેટિંગ્સ સાચવો',
    mr: 'सेटिंग्ज जतन करा',
    bn: 'সেটিংস সংরক্ষণ করুন',
    ta: 'அமைப்புகளைச் சேமி',
    te: 'సెట్టింగ్‌లను సేవ్ చేయండి',
    kn: 'ಸಂಯೋಜನೆಗಳನ್ನು ಉಳಿಸಿ',
    ml: 'ക്രമീകരണങ്ങൾ സംരക്ഷിക്കുക',
    pa: 'ਸੈਟਿੰਗਾਂ ਸੰਭਾਲੋ',
    es: 'Guardar Configuración',
    fr: 'Enregistrer les Paramètres',
    de: 'Einstellungen Speichern',
    ar: 'حفظ الإعدادات',
    zh: '保存系统配置',
    ja: '設定を保存',
    ru: 'Сохранить настройки',
  },
  'btn.export': {
    en: 'Export Dossier',
    hi: 'रिपोर्ट निर्यात करें',
    gu: 'અહેવાલ નિકાસ કરો',
    mr: 'अहवाल निर्यात करा',
    bn: 'ডোসিয়ার রপ্তানি করুন',
    ta: 'அறிக்கையை ஏற்றுமதி செய்',
    te: 'డోసియర్‌ను ఎగుమతి చేయండి',
    kn: 'ಡಾಕ್ಯುಮೆಂಟ್ ರಫ್ತು ಮಾಡಿ',
    ml: 'ഡോസിയർ കയറ്റുമതി ചെയ്യുക',
    pa: 'ਡੋਜ਼ੀਅਰ ਨਿਰਯਾਤ ਕਰੋ',
    es: 'Exportar Expediente',
    fr: 'Exporter le Dossier',
    de: 'Dossier Exportieren',
    ar: 'تصدير الملف الكامل',
    zh: '导出完整案卷',
    ja: '調書エクスポート',
    ru: 'Экспортировать досье',
  },
  'btn.openDesk': {
    en: 'Open in Review Desk',
    hi: 'रिव्यू डेस्क में खोलें',
    gu: 'સમીક્ષા ડેસ્કમાં ખોલો',
    mr: 'पुनरावलोकन डेस्कमध्ये उघडा',
    bn: 'পর্যালোচনা ডেস্কে খুলুন',
    ta: 'மதிப்பாய்வு டெஸ்க்கில் திறக்கவும்',
    te: 'రివ్యూ డెస్క్‌లో తెరవండి',
    kn: 'ಪರಿಶೀಲನಾ ಡೆಸ್ಕ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ',
    ml: 'റിവ്യൂ ഡെസ്കിൽ തുറക്കുക',
    pa: 'ਸਮੀਖਿਆ ਡੈਸਕ ਵਿੱਚ ਖੋਲ੍ਹੋ',
    es: 'Abrir en Mesa de Revisión',
    fr: 'Ouvrir au Poste d’Examen',
    de: 'Im Prüfplatz Öffnen',
    ar: 'فتح في مكتب المراجعة',
    zh: '在审查台开启深度检视',
    ja: '審査デスクで開く',
    ru: 'Открыть в криминалистическом столе',
  },

  // Risk Levels
  'risk.low': {
    en: 'CLEAR — Likely Authentic',
    hi: 'कम जोखिम — प्रमाणिक',
    gu: 'ઓછું જોખમ — અધિકૃત',
    mr: 'कमी धोका — अस्सल',
    bn: 'স্বচ্ছ — প্রামাণিক',
    ta: 'தெளிவானது — நம்பகமானது',
    te: 'క్లియర్ — అసలైనది',
    kn: 'ಸ್ಪಷ್ಟ — ಅಧಿಕೃತ',
    ml: 'വ്യക്തം — യഥാർത്ഥം',
    pa: 'ਸਪਸ਼ਟ — ਅਸਲੀ',
    es: 'LIBRE — Probablemente Auténtico',
    fr: 'CONFORME — Probablement Authentique',
    de: 'FREIGEGEBEN — Höchstwahrscheinlich Echt',
    ar: 'سليم — موثوق به غالباً',
    zh: '核验通过 — 真实有效',
    ja: 'クリア — 真正性確認',
    ru: 'ЧИСТО — Подлинный',
  },
  'risk.review': {
    en: 'REVIEW REQUIRED — Suspicious Signals',
    hi: 'समीक्षा आवश्यक — संदिग्ध संकेत',
    gu: 'સમીક્ષા જરૂરી — શંકાસ્પદ સંકેતો',
    mr: 'पुनरावलोकन आवश्यक — संशयास्पद सिग्नल',
    bn: 'পর্যালোচনা প্রয়োজন — সন্দেহজনক লক্ষণ',
    ta: 'மதிப்பாய்வு தேவை — சந்தேகத்திற்கிடமான குறிகாட்டிகள்',
    te: 'సమీక్ష అవసరం — అనుమానాస్పద సంకేతాలు',
    kn: 'ಪರಿಶೀಲನೆ ಅಗತ್ಯ — ಅನುಮಾನಾಸ್ಪದ ಸಂಕೇತಗಳು',
    ml: 'അവലോകനം ആവശ്യമാണ് — സംശയാസ്പദമായ സൂചനകൾ',
    pa: 'ਸਮੀਖਿਆ ਦੀ ਲੋੜ ਹੈ — ਸ਼ੱਕੀ ਸੰਕੇਤ',
    es: 'REVISIÓN REQUERIDA — Señales Sospechosas',
    fr: 'EXAMEN REQUIS — Indicateurs Suspects',
    de: 'PRÜFUNG ERFORDERLICH — Verdächtige Signale',
    ar: 'مراجعة مطلوبة — مؤشرات مشبوهة',
    zh: '需要复审 — 存在可疑信号',
    ja: '要確認 — 疑わしい兆候あり',
    ru: 'ТРЕБУЕТСЯ ПРОВЕРКА — Подозрительные признаки',
  },
  'risk.high': {
    en: 'HIGH RISK — Fraud Indicators Detected',
    hi: 'उच्च जोखिम — संभावित धोखाधड़ी',
    gu: 'ઉચ્ચ જોખમ — છેતરપિંડીના સંકેતો',
    mr: 'उच्च धोका — फसवणूक सूचक आढळले',
    bn: 'উচ্চ ঝুঁকি — প্রতারণার লক্ষণ শনাক্ত',
    ta: 'அதிக ஆபத்து — மோசடி குறிகாட்டிகள் கண்டறியப்பட்டன',
    te: 'అధిక ప్రమాదం — మోసం సూచికలు గుర్తించబడ్డాయి',
    kn: 'ಹೆಚ್ಚಿನ ಅಪಾಯ — ವಂಚನೆ ಸೂಚಕಗಳು ಪತ್ತೆಯಾಗಿವೆ',
    ml: 'ഉയർന്ന അപകടസാധ്യത — തട്ടിപ്പ് സൂചനകൾ കണ്ടെത്തി',
    pa: 'ਉੱਚ ਜੋਖਮ — ਧੋਖਾਧੜੀ ਦੇ ਸੰਕੇਤ ਮਿਲੇ',
    es: 'ALTO RIESGO — Indicadores de Fraude Detectados',
    fr: 'HAUT RISQUE — Indicateurs de Fraude Détectés',
    de: 'HOHES RISIKO — Betrugsmerkmale Erkannt',
    ar: 'خطر شديد — تم اكتشاف مؤشرات احتيال',
    zh: '极高风险 — 侦测到伪造欺诈迹象',
    ja: '高リスク — 偽造・改ざんの兆候を検知',
    ru: 'ВЫСОКИЙ РИСК — Обнаружены признаки подделки',
  },
  'risk.score': {
    en: 'Forensic Risk Index',
    hi: 'जोखिम स्कोर',
    gu: 'જોખમ સ્કોર',
    mr: 'जोखीम स्कोअर',
    bn: 'ঝুঁকি স্কোর',
    ta: 'ஆபத்து மதிப்பீடு',
    te: 'రిస్క్ స్కోరు',
    kn: 'ಅಪಾಯ ಸ್ಕೋರ್',
    ml: 'റിസ്ക് സ്കോർ',
    pa: 'ਜੋਖਮ ਸਕੋਰ',
    es: 'Índice de Riesgo Forense',
    fr: 'Indice de Risque Légal',
    de: 'Forensischer Risikoindex',
    ar: 'مؤشر المخاطر الجنائية',
    zh: '司法风险指数',
    ja: 'リスク評価指数',
    ru: 'Индекс риска',
  },

  // Auto-Lock
  'lock.warningTitle': {
    en: 'Inactivity Warning',
    hi: 'निष्क्रियता चेतावनी',
    gu: 'નિષ્ક્રિયતા ચેતવણી',
    mr: 'निष्क्रियता चेतावणी',
    bn: 'নিষ্ক্রিয়তার সতর্কতা',
    ta: 'செயலற்ற எச்சரிக்கை',
    te: 'నిష్క్రియ హెచ్చరిక',
    kn: 'ನಿಷ್ಕ್ರಿಯತೆಯ ಎಚ್ಚರಿಕೆ',
    ml: 'നിഷ്‌ക്രിയത്വ മുന്നറിയിപ്പ്',
    pa: 'ਅਕਿਰਿਆਸ਼ੀਲਤਾ ਚੇਤਾਵਨੀ',
    es: 'Advertencia de Inactividad',
    fr: 'Avertissement d’Inactivité',
    de: 'Inaktivitätswarnung',
    ar: 'تحذير عدم النشاط',
    zh: '无操作安全提醒',
    ja: '非アクティブ警告',
    ru: 'Предупреждение о неактивности',
  },
  'lock.warningMessage': {
    en: 'Your verification session will lock in 30 seconds to protect sensitive document information.',
    hi: 'संवेदनशील दस्तावेज़ जानकारी की सुरक्षा के लिए आपका सत्र 30 सेकंड में लॉक हो जाएगा।',
    gu: 'સંવેદનશીલ માહિતીની સુરક્ષા માટે તમારું સત્ર 30 સેકન્ડમાં લૉક થઈ જશે.',
    mr: 'संवेदनशील माहितीच्या संरक्षणासाठी तुमचे सत्र 30 सेकंदात लॉक होईल.',
    bn: 'সংবেদনশীল তথ্য সুরক্ষার জন্য আপনার সেশন ৩০ সেকেন্ডে লক হয়ে যাবে।',
    ta: 'உணர்திறன் வாய்ந்த தகவல்களைப் பாதுகாக்க உங்கள் அமர்வு 30 வினாடிகளில் பூட்டப்படும்.',
    te: 'సున్నితమైన సమాచారాన్ని రక్షించడానికి మీ సెషన్ 30 సెకన్లలో లాక్ చేయబడుతుంది.',
    kn: 'ಸೂಕ್ಷ್ಮ ಮಾಹಿತಿಯನ್ನು ರಕ್ಷಿಸಲು ನಿಮ್ಮ ಸೆಷನ್ 30 ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಲಾಕ್ ಆಗುತ್ತದೆ.',
    ml: 'രേഖകളുടെ സുരക്ഷയ്ക്കായി നിങ്ങളുടെ സെഷൻ 30 സെക്കൻഡിൽ ലോക്കാകും.',
    pa: 'ਸੰਵੇਦਨਸ਼ੀਲ ਜਾਣਕਾਰੀ ਦੀ ਸੁਰੱਖਿਆ ਲਈ ਤੁਹਾਡਾ ਸੈਸ਼ਨ 30 ਸਕਿੰਟਾਂ ਵਿੱਚ ਲਾਕ ਹੋ ਜਾਵੇਗਾ।',
    es: 'Su sesión de verificación se bloqueará en 30 segundos para proteger información confidencial.',
    fr: 'Votre session de vérification se verrouillera dans 30 secondes pour protéger les données confidentielles.',
    de: 'Ihre Sitzung wird in 30 Sekunden gesperrt, um vertrauliche Dokumentdaten zu schützen.',
    ar: 'سيتم قفل جلستك خلال 30 ثانية لحماية بيانات الوثائق الحساسة.',
    zh: '为保护旅客敏感信息，系统将在30秒后自动锁定当前会话。',
    ja: '機密文書データを保護するため、30秒後にセッションを自動ロックします。',
    ru: 'Сессия будет заблокирована через 30 секунд для защиты персональных данных.',
  },
  'lock.lockedTitle': {
    en: 'Verification Session Protected',
    hi: 'सत्यापन सत्र लॉक है',
    gu: 'સત્ર લૉક થયેલ છે',
    mr: 'सत्र लॉक आहे',
    bn: 'সেশন সুরক্ষিত ও লক করা হয়েছে',
    ta: 'அமர்வு பாதுகாக்கப்பட்டுள்ளது',
    te: 'సెషన్ లాక్ చేయబడింది',
    kn: 'ಸೆಷನ್ ಸುರಕ್ಷಿತವಾಗಿದೆ',
    ml: 'സെഷൻ സംരക്ഷിച്ചിരിക്കുന്നു',
    pa: 'ਸੈਸ਼ਨ ਸੁਰੱਖਿਅਤ ਹੈ',
    es: 'Sesión Protegida',
    fr: 'Session Protégée',
    de: 'Sitzung Geschützt',
    ar: 'جلسة التحقق مؤمنة',
    zh: '会话已受保护并锁定',
    ja: 'セッション保護ロック中',
    ru: 'Сессия защищена и заблокирована',
  },
  'lock.lockedMessage': {
    en: 'Document data is concealed for border security protocols. Click unlock to resume your inspection.',
    hi: 'सुरक्षा के लिए दस्तावेज़ डेटा छुपाया गया है। पुनः आरंभ करने के लिए अनलॉक करें।',
    gu: 'સુરક્ષા માટે દસ્તાવેજ છુપાયેલ છે. આગળ વધવા માટે અનલૉક કરો.',
    mr: 'सुरक्षेसाठी दस्तऐवज लपवला आहे. पुन्हा सुरू करण्यासाठी अनलॉक करा.',
    bn: 'সুরক্ষার জন্য তথ্য লুকানো আছে। পুনরায় শুরু করতে আনলক করুন।',
    ta: 'பாதுகாப்பிற்காக ஆவணத் தரவு மறைக்கப்பட்டுள்ளது. திறக்க கிளிக் செய்யவும்.',
    te: 'భద్రత కోసం పత్రం దాచబడింది. పునఃప్రారంభించడానికి అన్‌లాక్ చేయండి.',
    kn: 'ಸುರಕ್ಷತೆಗಾಗಿ ದಾಖಲೆ ಮರೆಮಾಡಲಾಗಿದೆ. ಮುಂದುವರಿಯಲು ಅನ್‌ಲಾಕ್ ಮಾಡಿ.',
    ml: 'സുരക്ഷയ്ക്കായി ഡാറ്റ മറച്ചിരിക്കുന്നു. പുനരാരംഭിക്കാൻ അൺലോക്ക് ചെയ്യുക.',
    pa: 'ਸੁਰੱਖਿਆ ਲਈ ਡੇਟਾ ਲੁਕਾਇਆ ਗਿਆ ਹੈ। ਜਾਰੀ ਰੱਖਣ ਲਈ ਅਨਲੌਕ ਕਰੋ।',
    es: 'Los datos del documento están ocultos por seguridad. Haga clic en desbloquear para continuar.',
    fr: 'Les données sont masquées pour des raisons de sécurité. Cliquez pour déverrouiller.',
    de: 'Dokumentdaten sind geschützt. Klicken Sie auf Entsperren, um fortzufahren.',
    ar: 'تم حجب بيانات الوثيقة لبروتوكولات الأمان. انقر لإلغاء القفل.',
    zh: '根据边境安全协议已隐藏证件隐私信息。点击解锁以继续检视。',
    ja: '国境警備プロトコルに基づき情報をマスクしています。クリックしてロック解除。',
    ru: 'Данные скрыты согласно протоколам безопасности. Нажмите разблокировать.',
  },

  // Settings
  'settings.appearance': {
    en: 'Appearance & Security Theme',
    hi: 'दिखावट और थीम',
    gu: 'દેખાવ અને થીમ',
    mr: 'दिसणे आणि थीम',
    bn: 'চেহারা ও থিম',
    ta: 'தோற்றம் மற்றும் தீம்',
    te: 'రూపం & థీమ్',
    kn: 'ಗೋಚರತೆ ಮತ್ತು ಥೀಮ್',
    ml: 'രൂപവും തീമും',
    pa: 'ਦਿੱਖ ਅਤੇ ਥੀਮ',
    es: 'Apariencia y Tema de Seguridad',
    fr: 'Apparence et Thème de Sécurité',
    de: 'Erscheinungsbild & Sicherheitstheme',
    ar: 'المظهر والسمة الأمنية',
    zh: '外观与安全视觉系统',
    ja: '外観・セキュリティテーマ',
    ru: 'Оформление и тема безопасности',
  },
  'settings.theme': {
    en: 'Color System',
    hi: 'थीम मोड',
    gu: 'થીમ મોડ',
    mr: 'थीम मोड',
    bn: 'থিম মোড',
    ta: 'தீம் முறைமை',
    te: 'థీమ్ మోడ్',
    kn: 'ಥೀಮ್ ಮೋಡ್',
    ml: 'തീം മോഡ്',
    pa: 'ਥੀਮ ਮੋਡ',
    es: 'Sistema de Color',
    fr: 'Système de Couleurs',
    de: 'Farbsystem',
    ar: 'نظام الألوان',
    zh: '色彩系统模式',
    ja: 'カラーシステム',
    ru: 'Цветовая схема',
  },
  'settings.language': {
    en: 'System Language / Locale',
    hi: 'सिस्टम भाषा',
    gu: 'સિસ્ટમ ભાષા',
    mr: 'सिस्टम भाषा',
    bn: 'সিস্টেম ভাষা',
    ta: 'கணினி மொழி',
    te: 'సిస్టమ్ భాష',
    kn: 'ಸಿಸ್ಟಮ್ ಭಾಷೆ',
    ml: 'സിസ്റ്റം ഭാഷ',
    pa: 'ਸਿਸਟਮ ਭਾਸ਼ਾ',
    es: 'Idioma del Sistema / Región',
    fr: 'Langue du Système / Région',
    de: 'Systemsprache / Region',
    ar: 'لغة النظام / الإقليم',
    zh: '系统语言 / 地区',
    ja: 'システム言語 / 地域',
    ru: 'Язык системы / Регион',
  },
  'settings.security': {
    en: 'Border Security & Auto-Lock',
    hi: 'सुरक्षा और ऑटो-लॉक',
    gu: 'સુરક્ષા અને ઑટો-લૉક',
    mr: 'सुरक्षा आणि ऑटो-लॉक',
    bn: 'সুরক্ষা ও স্বয়ংক্রিয় লক',
    ta: 'பாதுகாப்பு & தானியங்கு பூட்டு',
    te: 'భద్రత & ఆటో-లాక్',
    kn: 'ಭದ್ರತೆ ಮತ್ತು ಸ್ವಯಂ ಲಾಕ್',
    ml: 'സുരക്ഷയും സ്വയമേവയുള്ള ലോക്കും',
    pa: 'ਸੁਰੱਖਿਆ ਅਤੇ ਆਟੋ-ਲਾਕ',
    es: 'Seguridad Fronteriza y Bloqueo Automático',
    fr: 'Sécurité Frontalière & Verrouillage Automatique',
    de: 'Grenzschutz & Automatische Sperre',
    ar: 'أمن الحدود والقفل التلقائي',
    zh: '边防级安全与自动锁定',
    ja: '国境警備・自動ロック',
    ru: 'Пограничная безопасность и автоблокировка',
  },
  'settings.autoLock': {
    en: 'Auto-Lock Sensitive Inspection Windows',
    hi: 'संवेदनशील दस्तावेज़ स्वतः लॉक करें',
    gu: 'સંવેદનશીલ દસ્તાવેજો આપમેળે લૉક કરો',
    mr: 'संवेदनशील दस्तऐवज आपोआप लॉक करा',
    bn: 'সংবেদনশীল নথি স্বয়ংক্রিয়ভাবে লক করুন',
    ta: 'உணர்திறன் ஆவணங்களைத் தானாகப் பூட்டு',
    te: 'సున్నితమైన పత్రాలను ఆటో-లాక్ చేయండి',
    kn: 'ಸೂಕ್ಷ್ಮ ದಾಖಲೆಗಳನ್ನು ಸ್ವಯಂ ಲಾಕ್ ಮಾಡಿ',
    ml: 'രേഖകൾ സ്വയമേവ ലോക്ക് ചെയ്യുക',
    pa: 'ਸੰਵੇਦਨਸ਼ੀਲ ਦਸਤਾਵੇਜ਼ ਆਪਣੇ ਆਪ ਲਾਕ ਕਰੋ',
    es: 'Bloqueo Automático de Vistas Confidenciales',
    fr: 'Verrouillage Automatique des Données Sensibles',
    de: 'Automatische Sperre für Vertrauliche Daten',
    ar: 'قفل تلقائي لنوافذ التفتيش الحساسة',
    zh: '敏感审查窗口无操作自动加锁',
    ja: '機密審査画面の自動ロック',
    ru: 'Автоблокировка окон с персональными данными',
  },
};

interface LanguageContextType {
  language: Language;
  currentLanguageInfo: LanguageInfo;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultText?: string) => string;
  supportedLanguages: LanguageInfo[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  currentLanguageInfo: supportedLanguages[0],
  setLanguage: () => {},
  t: (key: string, defaultText?: string) => defaultText || key,
  supportedLanguages,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('veridoc-lang') as Language | null;
    const isValid = supportedLanguages.some((l) => l.code === stored);
    if (isValid && stored) {
      setLanguageState(stored);
      applyHtmlDir(stored);
    }
  }, []);

  const applyHtmlDir = (lang: Language) => {
    const info = supportedLanguages.find((l) => l.code === lang);
    if (info?.dir === 'rtl') {
      document.documentElement.setAttribute('dir', 'rtl');
    } else {
      document.documentElement.removeAttribute('dir');
    }
    document.documentElement.setAttribute('lang', lang);
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('veridoc-lang', lang);
    applyHtmlDir(lang);
  };

  const t = (key: string, defaultText?: string): string => {
    const entry = dictionary[key];
    if (entry && entry[language]) {
      return entry[language];
    }
    if (entry && entry['en']) {
      return entry['en'];
    }
    return defaultText || key;
  };

  const currentLanguageInfo =
    supportedLanguages.find((l) => l.code === language) || supportedLanguages[0];

  return (
    <LanguageContext.Provider
      value={{
        language,
        currentLanguageInfo,
        setLanguage,
        t,
        supportedLanguages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
